FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Scenius.CodeTest.API/Scenius.CodeTest.API.csproj", "Scenius.CodeTest.API/"]
RUN dotnet restore "Scenius.CodeTest.API/Scenius.CodeTest.API.csproj"
COPY . .
WORKDIR "/src/Scenius.CodeTest.API"
RUN dotnet build "Scenius.CodeTest.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Scenius.CodeTest.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Scenius.CodeTest.API.dll"]
